### ISSUE TITLE
Support for verbatim multipart/related S/MIME uploads

### ISSUE THREAD

**Issue by pke** [edeckers/react-native-blob-courier#135]
The library already supports 2 variants of multipart uploads, which covers most use-cases.

I have a third use-case now and wonder if this can be already done with the library or would become a feature request.

I have to upload S/MIME `multipart/related` bodies which I already prepare myself and place them in the apps storage folder like this `YYYYMMDDHHMMSSMS-<guid>.upload` The content of this file is the `multipart/related` body that needs to be uploaded. It must not be base64 encoded or anything.

Does this already work when pointing the request to this local file and setting the `Content-Type` header to `multipart/related`?

**Comment by edeckers** [comment]
Hi @pke , thank you for opening this issue! Indeed, this is a use-case that is not supported by the library; unfortunately your suggested workaround won't work, because the `multipart/form-data` header  is [hardcoded](https://github.com/edeckers/react-native-blob-courier/blob/develop/src/index.tsx#L151) and also because your file will be treated as any other regular file instead of a HTTP request.

As I see it, there are two ways to facilitate what you're looking for:
1. Add a `verbatimRequest` or `rawRequest` method which sends a file _supposedly_ containing a raw HTTP request to the target server
2. Extend the already existing `upload` facilities, by allowing you to set the `multipart/related` header and have the library add predictable `Content-ID's` to every part of the request

If I understand you correctly, you're suggesting (1)? Personally I'm leaning towards (2), since it fits better with the current premise of the library, which is to aid in building requests. Would (2) be a workable compromise for your needs or am I missing a crucial detail?

**Comment by pke** [comment]
Thanks for your quick an thorough response. 

I need this for S/MIME uploads. But I think that's out of scope for this lib. It could however help in composition of the multi layered related parts.

**Comment by edeckers** [comment]
Your comment makes total sense to me, and I think it would be a nice feature to add to the library. I'm still pondering what solution to go with though.

As for your suggested workaround: every upload request is [mapped](https://github.com/edeckers/react-native-blob-courier/blob/1049b4e0695d4f724e1635595dba7a336ef423b1/android/src/main/java/io/deckers/blob_courier/upload/BlobUploader.kt#L41) to a multipart body, so this won't work. This is what happens:
```tsx
const request0 = {
  absoluteFilePath,
  method: 'POST',
  mimeType: 'multipart/related; boundary="===============smime.parts=="',
  url: 'http://192.168.0.147:8080',
};

const uploadResult = await BlobCourier.uploadBlob(request0)
```
```
ely@xps-ely ~ nc -l 8080
POST / HTTP/1.1
Content-Type: multipart/form-data; boundary=b3e08e48-cfca-4423-a141-e1386c4bd0bb
Content-Length: 1015
Host: 192.168.0.147:8080
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.14.9

--b3e08e48-cfca-4423-a141-e1386c4bd0bb
Content-Disposition: form-data; name="file"; filename="test.upload"
Content-Type: multipart/related; boundary="===============smime.parts=="
Content-Length: 765

(...)
```

It makes a good point for the `verbatimBody` or `rawBody` solution we talked about earlier in this thread though, because that would definitely solve your problem right now.

I'll let you know what I decide on soon!

**Comment by edeckers** [comment]
I decided to implement both discussed solutions (#137 and #138); #137 will _probably_ be the first one I'll work on.

**Comment by edeckers** [comment]
Closing this in favor of the issues mentioned in my last coment.
