### ISSUE TITLE
[IOS] Accept ph:// assets for camera-roll uploads

### ISSUE THREAD

**Issue by vforvasile** [edeckers/react-native-blob-courier#157]
Hello @edeckers!

**Is your feature request related to a problem? Please describe.**
Would be very nice to be able to upload ph:// files without extra steps. 

**Describe the solution you'd like**
I can't really describe the solution. Someone opened a PR in another [library](https://github.com/Vydia/react-native-background-upload/pull/184) a while ago related to ph:// uploads

**Describe alternatives you've considered**
Copy a temporary file with react-native-fs then upload the temporary file then delete temporary file after upload is finished

Have a nice day!

**Comment by edeckers** [comment]
Hey! While I do understand your motivation for wanting this feature, I avoid adding any file system related feature by design: it seems to me that predecessors of `react-native-blob-courier` (e.g. [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob)) tried to include both file system and HTTP transfer functionality, which is what bit them eventually. Either because the library got to big to maintain, because Android moved to [Scoped Storage](https://developer.android.com/training/data-storage#scoped-storage), etc.

Therefore the alternative approach you described is exactly the way `react-native-blob-courier` is intended to be used. Which might be cumbersome and even suboptimal from a resource usage perspective, but it keeps `react-native-blob-courier` simple, focused and maintainable.

If you're looking for a combination of both filesystem and HTTP transfers you should check out [react-native-file-access](https://github.com/alpha0010/react-native-file-access), which is an initiative that just like `react-native-blob-courier` started in the wake of the `rn-fetch-blob` discontinuation.
