### ISSUE TITLE
Access to cached files via dynamically updated dictionary

### ISSUE THREAD

**Issue by arthur812812** [edeckers/react-native-blob-courier#207]
**Is your feature request related to a problem? Please describe.**
I want to use this library to cache files, so a user won't download them via the network if he has already fetched them once. After an app relaunch, there is no information about cached files (e.g. file path and date fetched). The only solution I found is to add something like `rn-fetch-blob` to access the app's cache directories. If I'm wrong, please correct me.

**Describe the solution you'd like**
I suggest adding a persistent dictionary that contains information about fetched requests(path to file, last date fetched, and so on) and making it available via `getFetchedBlobMap` or something like that

**Describe alternatives you've considered**
Maybe there is a better available solution around for this task than creating a dictionary? I'm not sure for now

**Additional context**
Thank you for working with this library! It looks interesting and modern, compared to other solutions around.

**Comment by edeckers** [comment]
Hi @arthur812812 , thank you for reaching out and thank you for your compliment!

If I understand correctly, you're looking to do this:
1. Fetch https://example.com/myfile.bin to `/path/to/cache`
2. Restart the app
3. Use the file acquired in step 1, without downloading it again, because it is already there

This is out of scope for `react-native-blob-courier` as this library purely focuses on sending and receiving large data; accessing this data from disk should be done through other libraries. Instead of `rn-fetch-blob` I would like to recommend https://github.com/alpha0010/react-native-file-access though, because the latter is newer, less complex and is actively maintained. I also saw `rn-fetch-blob` has been brought back to life a couple of months or so ago, but up until then it had been unmaintained since 2020, so I'm not too sure what their plans are for the future.

As for your suggested solution:
>I suggest adding a persistent dictionary that contains information about fetched requests(path to file, last date fetched, and so on) and making it available via getFetchedBlobMap or something like that

I also feel this is out of scope for the library as it seems to me that which meta data is and is not relevant is dictated by the business logic of your app. So, if I'm interpreting your situation correctly and if I were in your shoes I would simply persist the meta data returned by the `react-native-blob-courier` requests as a dictionary in `AsyncStorage`. Does that work for you?

**Comment by arthur812812** [comment]
Greetings @edeckers, thank you for the quick reply 

You understood me correctly, that's exactly what I'm willing to do. This issue could be closed.

**Comment by edeckers** [comment]
Alright, glad I could help :)
